package soft;


import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import java.util.logging.Level;
import java.sql.SQLException;

import java.util.logging.Logger;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.border.Border;
import javax.swing.JOptionPane;

//import FProject.login;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
Border field_border = BorderFactory.createMatteBorder(1, 5, 1, 1, Color.white);
        jTextField_fname.setBorder(field_border);
        jTextField_lname.setBorder(field_border);
        jTextField_phone.setBorder(field_border);
        jTextField_adress.setBorder(field_border);
        jPasswordField_pass1.setBorder(field_border);
        jPasswordField_pass2.setBorder(field_border);
        jTextField_g.setBorder(field_border);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField_lname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField_fname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField_phone = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_adress = new javax.swing.JTextField();
        jPasswordField_pass2 = new javax.swing.JPasswordField();
        jPasswordField_pass1 = new javax.swing.JPasswordField();
        jTextField_g = new javax.swing.JTextField();
        go = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 600));
        jPanel2.setLayout(null);

        jTextField_lname.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        jTextField_lname.setToolTipText("First Name");
        jTextField_lname.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTextField_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_lnameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_lname);
        jTextField_lname.setBounds(20, 150, 350, 40);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(155, 91, 97));
        jLabel1.setText("First Name");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 50, 100, 30);

        jButton1.setBackground(new java.awt.Color(110, 48, 48));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SIGN UP");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(140, 510, 150, 40);
        jButton1.getAccessibleContext().setAccessibleName("SIGNUP");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(155, 91, 97));
        jLabel5.setText("Last Name");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 120, 100, 30);

        jTextField_fname.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        jTextField_fname.setToolTipText("First Name");
        jTextField_fname.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTextField_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_fnameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_fname);
        jTextField_fname.setBounds(20, 80, 350, 40);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(155, 91, 97));
        jLabel6.setText("Phone Number");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 190, 140, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 34)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(181, 142, 142));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Creat New Account");
        jLabel3.setName(""); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 390, 40);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(155, 91, 97));
        jLabel10.setText("Confirm ");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 450, 80, 30);

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(155, 91, 97));
        jLabel12.setText("Gender");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 280, 80, 40);

        jTextField_phone.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        jTextField_phone.setToolTipText("First Name");
        jTextField_phone.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTextField_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_phoneActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_phone);
        jTextField_phone.setBounds(20, 220, 350, 40);

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(155, 91, 97));
        jLabel13.setText("Address");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(20, 340, 90, 30);

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(155, 91, 97));
        jLabel14.setText("Password");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(20, 390, 90, 50);

        jTextField_adress.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        jTextField_adress.setToolTipText("First Name");
        jTextField_adress.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTextField_adress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_adressActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_adress);
        jTextField_adress.setBounds(120, 340, 250, 40);

        jPasswordField_pass2.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        jPasswordField_pass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_pass2ActionPerformed(evt);
            }
        });
        jPanel2.add(jPasswordField_pass2);
        jPasswordField_pass2.setBounds(120, 450, 250, 40);

        jPasswordField_pass1.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        jPasswordField_pass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_pass1ActionPerformed(evt);
            }
        });
        jPanel2.add(jPasswordField_pass1);
        jPasswordField_pass1.setBounds(120, 400, 250, 40);

        jTextField_g.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        jPanel2.add(jTextField_g);
        jTextField_g.setBounds(120, 280, 250, 40);

        go.setBackground(new java.awt.Color(110, 48, 48));
        go.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        go.setForeground(new java.awt.Color(255, 255, 255));
        go.setText("GO BACK");
        go.setActionCommand("");
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });
        jPanel2.add(go);
        go.setBounds(310, 530, 90, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft/original.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jLabel2.setPreferredSize(new java.awt.Dimension(400, 600));
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_fnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
      /*  String str_url="jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con=DriverManager.getConnection (str_url,"rahaf","123456");
            Statement stmt=con.createStatement();*/
         String fname = jTextField_fname.getText();
         String lname = jTextField_lname.getText();
         String adress = jTextField_adress.getText();
         String gender = jTextField_g.getText();
         String phone = jTextField_phone.getText();

         String pass1 = String.valueOf(jPasswordField_pass1.getPassword());
         String pass2 = String.valueOf(jPasswordField_pass2.getPassword());
         //   passward=this.password1.  getText();
     //    int length = phone.length();         if (length>7) jTextField_phone.setEditable(true);

              if(fname.trim().equals("") || lname.trim().equals("") || phone.trim().equals("")||gender.trim().equals("")
           || pass1.trim().equals("") || pass2.trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "One Or More Fields Are Empty Please Full It","Empty Fields",2);
          //  return false;
        }
        
        // check if the two password are equals or not
        else if(!pass1.equals(pass2))
        {
           JOptionPane.showMessageDialog(null, "Password Doesn't Match try agin","Confirm Password",2); 
         //  return false;
        }
        
        // if everything is ok
     //   else{JOptionPane.showMessageDialog(null, "succesfully");
           // return true;
        else{
            
        
       
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_lnameActionPerformed

    private void jTextField_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_phoneActionPerformed

    private void jTextField_adressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_adressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_adressActionPerformed

    private void jPasswordField_pass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_pass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_pass2ActionPerformed

    private void jPasswordField_pass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_pass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_pass1ActionPerformed

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        // TODO add your handling code here:
           login form = new login();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                // close the current form(login form)
                this.dispose();
        
        
    }//GEN-LAST:event_goActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton go;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField_pass1;
    private javax.swing.JPasswordField jPasswordField_pass2;
    private javax.swing.JTextField jTextField_adress;
    private javax.swing.JTextField jTextField_fname;
    private javax.swing.JTextField jTextField_g;
    private javax.swing.JTextField jTextField_lname;
    private javax.swing.JTextField jTextField_phone;
    // End of variables declaration//GEN-END:variables
}
