package soft;

import javax.swing.JOptionPane;

//import javaapplication2.SignUp;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax .swing.JOptionPane;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import oracle.jdbc.pool.OracleDataSource;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author user
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordField11 = new javax.swing.JPasswordField();
        jTextField1_phone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton2.setBackground(new java.awt.Color(136, 75, 87));
        jButton2.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sign up");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(210, 500, 80, 25);

        jLabel5.setBackground(new java.awt.Color(242, 213, 213));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(144, 75, 88));
        jLabel5.setText("Don’t have an account?");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 490, 170, 40);

        jButton1.setBackground(new java.awt.Color(136, 75, 87));
        jButton1.setFont(new java.awt.Font("Verdana", 0, 34)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(110, 340, 160, 60);

        jPasswordField11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField11FocusLost(evt);
            }
        });
        jPasswordField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField11ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField11);
        jPasswordField11.setBounds(20, 260, 330, 50);

        jTextField1_phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1_phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1_phoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1_phoneFocusLost(evt);
            }
        });
        jTextField1_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_phoneActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1_phone);
        jTextField1_phone.setBounds(20, 150, 330, 50);

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(124, 54, 67));
        jLabel4.setText("PASSWORD");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 220, 130, 40);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(124, 54, 67));
        jLabel3.setText("PHONE NUMBER");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 100, 160, 60);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GetOrganized");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 20, 320, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft/fc4ba00562c09a13a28923597e39683b.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -20, 390, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_phoneActionPerformed

    }//GEN-LAST:event_jTextField1_phoneActionPerformed

    private void jPasswordField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 
PreparedStatement st;
      ResultSet rs;
        
        // get the username & password
        String phone = jTextField1_phone.getText();
        String password = String.valueOf(jPasswordField11.getPassword());
        

        // show a message if the username or the password fields are empty
        if(phone.trim().equals("  "))
        {
            JOptionPane.showMessageDialog(null, "Enter Your phone", "Empty phone", 2);
        }
        else if(password.trim().equals("  "))
        {
            JOptionPane.showMessageDialog(null, "Enter Your Password", "Empty Password", 2);
        }
        
        // admin
         
             else{
                  try {
      
        
       OracleDataSource ods=new OracleDataSource();
            ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
            ods.setUser("system");
            ods.setPassword("Abcabc11");
            Connection conn=ods.getConnection();
            Statement st1=conn.createStatement();
            
            ResultSet r=st1.executeQuery("select * from signup");
            
            while(r.next()){
            
            String pass=r.getString(6);
            String ph=r.getString(1);
            
            if( password.equals(pass)&&phone.equals(ph)){
            this.setVisible(false);
            P11 p=new P11();
            p.setVisible(true);
            
            }
            }
            
            }catch (SQLException ex) {
         Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }     }
      

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 this.setVisible(false);
 SignUp signup=new SignUp();
signup.setVisible(true);
signup.pack();
signup.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1_phoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_phoneFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_phoneFocusGained

    private void jTextField1_phoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_phoneFocusLost
        //if textphone empty
        if(jTextField1_phone.getText().trim().equals("")){
         JOptionPane.showMessageDialog(null,"the PHONE is empty");

            jTextField1_phone.setText("");
            
        }
       
    }//GEN-LAST:event_jTextField1_phoneFocusLost

    private void jPasswordField11FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField11FocusLost
         // if the password field is equal to password or empty
        // we will set the "password" text in the field 
        // on focus lost event
        
        // get the password text
        String pass = String.valueOf(jPasswordField11.getPassword());
        
        if(pass.trim().equals("")  )
          
   {         JOptionPane.showMessageDialog(null,"the PASSWARD is empty");

            jPasswordField11.setText(" ");
           
        }
    }//GEN-LAST:event_jPasswordField11FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                login ln=new login();
                ln.setVisible(true);
                ln.pack();
                ln.setLocationRelativeTo(null);
               
                    }
        });
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HomePage form = new HomePage();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
               
                    }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField11;
    private javax.swing.JTextField jTextField1_phone;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    private void systemExit() {
WindowEvent winCloseing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);    }

    
}
